// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj90GwtXtyO6J3RfjMlw4sDMoaSgEJTTM',
    appId: '1:1037188634069:web:68add1b36202bf3cf3195c',
    messagingSenderId: '1037188634069',
    projectId: 'echocart-app',
    authDomain: 'echocart-app.firebaseapp.com',
    storageBucket: 'echocart-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI2021c96rUDxDc2JxOJ_5ePZnP8gwlYU',
    appId: '1:1037188634069:android:84cb4f9bebf24d05f3195c',
    messagingSenderId: '1037188634069',
    projectId: 'echocart-app',
    storageBucket: 'echocart-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFldOWbjFq4huSKMxkyNb0b4D-yJUE3eo',
    appId: '1:1037188634069:ios:de551e17b3efdf0af3195c',
    messagingSenderId: '1037188634069',
    projectId: 'echocart-app',
    storageBucket: 'echocart-app.appspot.com',
    iosBundleId: 'com.example.ecoAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFldOWbjFq4huSKMxkyNb0b4D-yJUE3eo',
    appId: '1:1037188634069:ios:4dba8e8ae4d03964f3195c',
    messagingSenderId: '1037188634069',
    projectId: 'echocart-app',
    storageBucket: 'echocart-app.appspot.com',
    iosBundleId: 'com.example.ecoAdminApp.RunnerTests',
  );
}
